### ISSUE TITLE
>In Ava, after you click "I do not like the result". There is no response. I think we need either make it darker or show the number of unlike instead of still grey
                    
               

### ISSUE THREAD

**Issue by boardxsupport** [boardx/BoardX-Community#359]
>In Ava, after you click "I do not like the result". There is no response. I think we need either make it darker or show the number of unlike instead of still grey
                    
                    >userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
                    email: xuyong007@gmail.com
                    username: xuyong007

**Comment by usamshen2** [comment]
It should trigger color change of the icon, it is not showing right?  Can you attach an image? Thanks

Usam

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: boardxsupport ***@***.***>
Sent: Tuesday, March 19, 2024 10:38:19 AM
To: boardx/BoardX-Community ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [boardx/BoardX-Community] >In Ava, after you click "I do not like the result". There is no response. I think we need either make it darker or show the number of unlike instead of still grey (Issue #359)


In Ava, after you click "I do not like the result". There is no response. I think we need either make it darker or show the number of unlike instead of still grey

                >userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
                email: ***@***.***
                username: xuyong007
